#pragma config(Motor,  motorA,          ,              tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorB,          ,              tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorC,          ,              tmotorNormal, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma  platform(NXT)
#include "writeFile4f.c"

const string  sFileName = "Vel_Iden.txt";  // file name

task main()
{
   long i = 0;
	 long pos_encoder=0;
	 float acontrol=40.0;
	 float pultorad = (2*PI/360);
	 float velocidad;
	 float pos_rad_ant=0;
	 float ts = 0.02;

	 	 float pos_rad;

   nMotorEncoder[motorA] = 0;
   Delete(sFileName,nIoResult);
   createTextFile(sFileName, 30000);
   i=0;

   while(i < 100)
      {
	    // reseteamos el temporizador para empezar el bucle de control
		  ClearTimer(T1);

		  // leemos el valor del encoder (medida: PULSOS)//2PI/360
		  pos_encoder=nMotorEncoder[motorA];
		  pos_rad = pos_encoder * pultorad;

		  // conversión D/A para control de los motores
		  motor[motorA] = acontrol;

		  //calculo de la velocidad
		  velocidad = (pos_rad - pos_rad_ant) /(ts);

		  pos_rad_ant = pos_rad;

		  // escribimos en el fichero 2 datos (un integer y un real) y un salto de linea
		  writeFloatNumber(velocidad);
		  writeFloatNumber(acontrol);

	          writeNewLine();


		// medimos el tiempo transcurrido para verificamos el periodo de muestreo
		while(time1(T1)<20)
		{
			// mientras que no hayan transcurrido 20mS, esperamos
			wait1Msec(4);
		}

		// incrementamos el valor del contador para fin de programa
		i++;
       }   // while
   // cerramos el fichero de texto
   closeWriteTextFile();

}  // main
